### PR TITLE
Adding the ability to deserialize subclasses of Geometry instead of Geometry only.

### PR DESCRIPTION
**Pull request by purpleP**
When I've started to work on this I haven't seen that some peoples already did that.
However I've changed the code much more then in previous pull requests.

I've removed smelly if else statements from deserializer.
I've removed code duplication from tests and made them more granular.
Also the roundtrip test wasn't working with JTS 1.8 maybe because of some changes in JTS. Anyway I think it shouldn't have been work. Because Geometry equals method is not overriden, it's overloaded. I've used equalsExact for comparing Geometries.

Third change is using gradle instead of maven. I'm not sure how to publish gradle based project to maven but I know it's possible and the old version haven't been published anyway.

Please reply on what you're planning to do with my code. If you wouldn't I would probably publish it myself.

### CODE REVIEW

**Comment by akbertram** [comment]
Hey! You rewrote my library :-)

**Comment by akbertram** [comment]
Looks pretty good, give me a couple days to look over the code and merge the previous pull requests, which I hadn't seen either. Thanks!

**Comment by purpleP** [comment]
After you will merge this pull request I would create another, which refines gradle build file so that this project artifact would be available at jitpack.io. I've already tested it. Also I've changed readme to reflect that fact that people now can just add jitpack repository to gradle and this library as a dependency.

**Comment by purpleP** [comment]
@akbertram Hey, you've still not merged it. Please review the code and do the merge. Also I'm thinking about adding the ability to serialize/deserialize crs field.

**Pull request merged**
